#! /bin/bash

#################### HACKADROID ######################
# Project - Hackadroid
# access any android devices remotely               
# Author: Ashish Singh (ashishsingh103020@gmail.com)
# Date: 25 Dec 2020
# Copyright (c) 2020
######################################################

#colors
white="\033[1;37m"                                          ##
grey="\033[0;37m"                                           ##
purple="\033[0;35m"                                         ##
red="\033[1;31m"                                            ##
lred="\033[0;91m"                                           ##
green="\033[1;32m"                                          ##
lgreen="\033[0;92m"                                         ##
yellow="\033[1;33m"                                         ##
purple="\033[0;35m"                                         ##
cyan="\033[0;36m"                                           ##
cyan1="\033[1;36m"                                          ##
cafe="\033[0;33m"                                           ##
fiuscha="\033[0;35m"                                        ##
blue="\033[1;34m"                                           ##
nc="\e[0m"

dir=`pwd`
user_id="$(logname)"
ngrok_url_login="https://dashboard.ngrok.com/login"
ngrok_url_signup="https://dashboard.ngrok.com/signup"
hackadroid_install="/usr/share"
clone="${hackadroid_install}/hackadroid"
msf_install="${hackadroid_install}/hackadroid"

############### main setup ######################

main_setup() {
	[ -d "${clone}" ] && rm -rf $clone > /dev/null 2>&1
	xterm -T "HACKADROID INSTALL" -e "git clone https://github.com/Bhaviktutorials/hackadroid.git ${clone}"
}

############# end of main setup ##################

msg() {
	printf "${blue}[-] ${green}${1}\n${nc}"
}

norm_msg() {
	printf "${green}${1}\n${nc}"
}

error_msg() {
        printf "${red}[ ! ] ${white}${1}\n${nc}"
}

function check_root() {
        if [ "$(whoami &2>/dev/null)" != "root" ] && [ "$(id -un &2>/dev/null)" != "root" ]
	then
                echo;
                error_msg "admin user detected"
                echo;
                error_msg "you must be root to run this script!"
                echo;
                error_msg "use 'sudo !!'"
                echo;
                exit 1
	fi
}

#spinner
spinner() {
        pid=$!
        spin='\|/-'
        i=0
        tput civis
        while kill -0 $pid 2>/dev/null
	do
                i=$(( (i+1) %4 ))
                printf "\r${cyan1}[${spin:$i:1}]${nc} ${cyan1} $launch"
                sleep .1
	done
        printf "\r   ${green}[✔]${nc} ${green} $splashdown"
        sleep 1;echo
        tput cnorm
}

function check_net() {
        ping -c 1 google.com > /dev/null 2>&1
        if [[ "$?" != 0 ]]
        then
                error_msg "No Inernet"
                exit 1
        fi
}

os_release() {
	if [ -e ${PREFIX}/bin/termux-info ]; then
		OS=TERMUX
		echo termux 
		exit 1
	fi
}

#mirror script for stable download speed

mirror() {
	launch="checking for update"
	splashdown="checked for update" ; echo
	(sudo apt update -y > /dev/null 2>&1 && sudo apt install git xterm -y > /dev/null 2>&1 ) & spinner;echo -e "\e[0m"
	launch="installing mirror script"
	splashdown="mirror script installed"
	(xterm -T "HACKADROID SETUP" -e "git clone https://github.com/IceM4nn/mirrorscript-v2.git && cd mirrorscript-v2 && chmod +x * && python3 mirrorscript-v2.py -v -https -src && cd .. && rm -rf mirrorscript-v2 > /dev/null && apt-get autoclean && sudo apt update -y && sudo apt install libpq-dev libpcap-dev libsqlite3-dev whiptail -y") & spinner;echo -e "\e[0m"
}

ngrok_yml() {
	head -n1 ~/.ngrok2/ngrok.yml > ngrok.txt
        echo "tunnels:
  first:
    addr: 4567
    proto: tcp    
  second:
    addr: 80
    proto: http " >> ngrok.txt
        cat ngrok.txt > ~/.ngrok2/ngrok.yml
        rm -rf ngrok.txt
}

check_dependencies () {		
	echo -ne '\e[8;41;95t' 
	clear
	echo -e $white
        echo "Hackadroid Framework v1.0.1"
        echo -e $yellow	
	echo "Checking for hackadroid dependencies"
	echo
	# METASPLOIT-FRAMEWORK
	which msfconsole > /dev/null 2>&1
        if [ "$?" -eq "0" ]; then		
                echo -e $green "[ ✔ ] Metasploit-Framework..............${lgreen}[ found ]"
                sleep 2		
        else		
                echo -e $red "[ X ] Metasploit-Framework.............. ..${lred}[ missing! ]"
                sleep 2              
                xterm -T "Hackadroid" -e "sudo apt-get install metasploit-framework -y" 
		sleep 1                                      
	fi       
	# ZENITY
	echo
        which zenity > /dev/null 2>&1
        if [ "$?" -eq "0" ]; then		
                echo -e $green "[ ✔ ] Zenity............................${lgreen}[ found ]"
                sleep 2
	else		
                echo -e $red "[ X ] Zenity.............................${lred}[ missing! ]"
                sleep 2              
                xterm -T "Hackadroid" -e "sudo apt-get install zenity -y" 
		sleep 1                
	fi	
	# ANDROID_FRAMEWORK_RES	
	echo
        which aapt > /dev/null 2>&1
        if [ "$?" -eq "0" ]; then
                echo -e $green "[ ✔ ] Aapt..............................${lgreen}[ found ]"
                sleep 2
	else
                echo -e $red "[ X ] Android-framewrok-res................${lred}[ missing! ]"
                sleep 2              
                xterm -T "Hackadroid" -e "sudo apt-get install android-framework-res -y" 
		xterm -T "Hackadroid" -e "sudo apt-get install aapt -y"
		sleep 1              
	fi
	# APKTOOL
        echo	
        which apktool > /dev/null 2>&1
        if [ "$?" -eq "0" ]; then
                echo -e $green "[ ✔ ] Apktool...........................${lgreen}[ found ]"
                sleep 2
        else
                echo -e $red "[ X ] Apktool.............................${lred}[ missing! ]"
                sleep 2              
                xterm -T "Hackadroid" -e "sudo apt-get install apktool -y" 
		sleep 1                
	fi
	# ZIPALIGN
	echo
        which zipalign > /dev/null 2>&1
        if [ "$?" -eq "0" ]; then
                echo -e $green "[ ✔ ] Zipalign..........................${lgreen}[ found ]"               
                sleep 2
        else
                echo -e $red "[ X ] Zipalign.............................${lred}[ missing! ]"
                sleep 2              
                xterm -T "Hackadroid" -e "sudo apt-get install zipalign -y" 
		sleep 1                
	fi
	# DEFAULT-JDK
	echo
        which java > /dev/null 2>&1
        if [ "$?" -eq "0" ]; then
                echo -e $green "[ ✔ ] Default-jdk.......................${lgreen}[ found ]"                
                sleep 2
        else
                echo -e $red "[ X ] Default-jdk..........................${lred}[ missing! ]"
                sleep 2
                xterm -T "Hackadroid" -e "sudo apt-get install default-jdk -y"
		sleep 1                
	fi
	# BC
	echo
        which bc > /dev/null 2>&1
        if [ "$?" -eq "0" ]; then
                echo -e $green "[ ✔ ] Bc................................${lgreen}[ found ]"               
                sleep 2
        else
                echo -e $red "[ X ] Bc..............................  ..${lred}[ missing! ]"
                sleep 2
                xterm -T "Hackadroid" -e "sudo apt-get install bc -y"
		sleep 1                
	fi
	# JQ
	echo
        which jq > /dev/null 2>&1
        if [ "$?" -eq "0" ]; then
                echo -e $green "[ ✔ ] Jq................................${lgreen}[ found ]"                
                sleep 2
        else
                echo -e $red "[ X ] Jq...................................${lred}[ missing! ]"
                sleep 2
                xterm -T "Hackadroid" -e "sudo apt-get install jq -y"
		sleep 1                
	fi
	# CURL
	echo
        which curl > /dev/null 2>&1
        if [ "$?" -eq "0" ]; then
                echo -e $green "[ ✔ ] Curl..............................${lgreen}[ found ]"              
                sleep 2
        else
                echo -e $red "[ X ] Curl.................................${lred}[ missing! ]"
                sleep 2
                xterm -T "Hackadroid" -e "sudo apt-get install curl -y"
		sleep 1                
	fi
	# LIBNOTIFY-BIN
	echo
        which notify-send > /dev/null 2>&1
        if [ "$?" -eq "0" ]; then
                echo -e $green "[ ✔ ] Libnotify-bin.....................${lgreen}[ found ]"                
                sleep 2
        else
                echo -e $red "[ X ] libnotify-bin........................${lred}[ missing! ]"
                sleep 2
                xterm -T "Hackadroid" -e "sudo apt-get install libnotify-bin -y"
		                
	fi
	# XDG-UTILS
	echo
        which xdg-open > /dev/null 2>&1
        if [ "$?" -eq "0" ]; then
                echo -e $green "[ ✔ ] Xdg-utils.........................${lgreen}[ found ]"            
                sleep 2
        else
                echo -e $red "[ X ] Xdg-utils............................${lred}[ missing! ]"
                sleep 2
                xterm -T "Hackadroid" -e "sudo apt-get install xdg-utils -y"
	fi
	# JARSIGNER
	echo
        which jarsigner > /dev/null 2>&1
        if [ "$?" -eq "0" ]; then
                echo -e $green "[ ✔ ] Jarsigner..........................${lgreen}[ found ]"
                sleep 2
        else
                echo -e $red "[ X ] Jarsigner............................${lred}[ missing! ]"
                sleep 2
                xterm -T "Hackadroid" -e "sudo apt-get install default-jdk -y"
		sleep 1
	fi
	# GNOME-TERMINAL
	echo
        which gnome-terminal > /dev/null 2>&1
        if [ "$?" -eq "0" ]; then
                echo -e $green "[ ✔ ] Gnome-terminal....................${lgreen}[ found ]"                
                sleep 2
        else
                echo -e $red "[ X ] Gnome-terminal.......................${lred}[ missing! ]"
                sleep 2              
                xterm -T "Hackadroid" -e "sudo apt-get install gnome-terminal -y" 		         
	fi
	# APACHE2
	echo
        which apache2 > /dev/null 2>&1
        if [ "$?" -eq "0" ]; then
                echo -e $green "[ ✔ ] Apache2...........................${lgreen}[ found ]"               
                sleep 2
        else
                echo -e $red "[ X ] Apache2..............................${lred}[ missing! ]"
                sleep 2
                xterm -T "Hackadroid" -e "sudo apt-get install apache2 -y"                
	fi
	# WGET
	echo
        which wget > /dev/null 2>&1
        if [ "$?" -eq "0" ]; then
                echo -e $green "[ ✔ ] Wget..............................${lgreen}[ found ]"                
                sleep 2
        else
                echo -e $red "[ X ] Wget.................................${lred}[ missing! ]"
                sleep 2
                xterm -T "Hackadroid" -e "sudo apt-get install wget -y"		                
	fi
	# NGROK
	echo
        which ngrok > /dev/null 2>&1
        if [ "$?" -eq "0" ]; then
                echo -e $green "[ ✔ ] Ngrok.............................${lgreen}[ found ]"                
                sleep 2
        else
                echo -e $red "[ X ] Ngrok................................${lred}[ missing! ]"
                sleep 2
                xterm -T "Hackadroid" -e "wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip"
		unzip ngrok-stable-linux-amd64.zip > /dev/null 2>&1 && rm -rf ngrok-stable-linux-amd64.zip > /dev/null 2>&1
		rm -rf ~/.ngrok2/ngrok.yml > /dev/null 2>&1
		login_signup=$(zenity --question --title "NGROK" --text "Already have an ngrok account" --width 300 --height 100 2> /dev/null)
		if [ $? -eq 0 ];then
			sudo -u $user_id -H firefox --new-tab $ngrok_url_login > /dev/null 2>&1 &
			sleep 25
		else
			sudo -u $user_id -H firefox --new-tab $ngrok_url_signup > /dev/null 2>&1 &
			sleep 25
		fi
                ngrok_token=$(zenity --title "NGROK TOKEN" --text "enter your ngrok authtoken" --entry --entry-text "./ngrok authtoken <your_auth_token>" --width 300 --height 120 2> /dev/null) && $ngrok_token >> /dev/null 2>&1 && mv ngrok /usr/bin > /dev/null 2>&1              
	fi
}

install_msf() {	
	launch="patching msf update"
	splashdown="patched msf update" ;echo
	(xterm -T "UPDATE MSF" -e "wget https://raw.githubusercontent.com/just-hack/hackadroid-setup/main/metasploit-framework.zip -O ${msf_install}/metasploit-framework.zip" && unzip ${msf_install}/metasploit-framework.zip -d ${msf_install} > /dev/null 2>&1) & spinner;echo -e "\e[0m"
	rm -rf ${msf_install}/metasploit-framework.zip > /dev/null 2>&1   	
	launch="Fetching gem"
	splashdown="Fetched gem"
	(xterm -T "BUNDLE & GEMS INSTALLATION" -e "cd ${msf_install}/metasploit-framework* && sudo gem install bundler:1.17.3 && bundle install && cd ${dir} && sleep 6 && echo [ ! ] done setup && sleep 3") & spinner;echo -e "\e[0m"
}

check_msf() {
	if [ -d "${msf_install}/metasploit-framework-5.0.101" ];then
		msf=true
	else
		install_msf
	fi
}

#final touchup

function final_touch() {	
        cp -rf ${msf_install}/hackadroid /usr/bin > /dev/null 2>&1 && chmod 777 /usr/bin/hackadroid /dev/null 2>&1
}

finish_setup() {
        {
    for ((i = 0 ; i <= 100 ; i+=1)); do
        sleep 0.1
        echo $i
    done
} | whiptail --gauge "setting up hackadroid please wait..." 6 50 0
}

#### ACTION ####

check_net
check_root
os_release
mirror
main_setup
check_dependencies
check_dependencies
check_msf
ngrok_yml
final_touch
finish_setup

#### DONE ####

############################## THANKYOU FOR INSTALLING ########################################

###############################################################################################


